name: pixel_rentverse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  introduction_screen: ^4.0.0
  lucide_icons_flutter: ^3.1.9

  flutter_secure_storage: ^10.0.0
  json_annotation: ^4.9.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  formz: ^0.8.0
  rxdart: ^0.28.0
  intl: ^0.20.2
  talker_bloc_logger: ^5.1.9
  talker_dio_logger: ^5.1.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png" 
  adaptive_icon_background: "#2A14B4"