name: pixel_rentverse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  introduction_screen: ^4.0.0
  lucide_icons_flutter: ^3.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
