name: pixel_rentverse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  introduction_screen: ^4.0.0
  lucide_icons_flutter: ^3.1.9

  flutter_secure_storage: ^10.0.0
  json_annotation: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
